apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: nextjs-openshift
  name: nextjs-openshift
spec:
  output:
    to:
      kind: DockerImage
      name: docker.io/hmeshal712/nextjs-openshift
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
