library identifier: "pipeline-library@v1.5",
retriever: modernSCM(
  [
    $class: "GitSCMSource",
    remote: "https://github.com/haider-meshal/openshift.git"
  ]
)

appName = "nextjs-openshift"

pipeline {
    agent { label "node12" }
    stages {
        stage("Checkout") {
            steps {
                checkout scm
            }
        }
        stage("Docker Build") {
            steps {
                binaryBuild(buildConfigName: appName, buildFromPath: "./nextjs-openshift")
            }
        }
    }
}
